---
# ConfigMap para variables de base de datos
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: carloscabreravas-dev
data:
  db-port: "5432"
  db-name: "microservicio"
  db-host: "postgres"

---
# ConfigMap para variables de entorno
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservicio-config
  namespace: carloscabreravas-dev
data:
  DEBUG: "false"
  APP_NAME: "Microservicio API"
  API_VERSION: "1.0.0"

---
# Secret para credenciales de base de datos
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: carloscabreravas-dev
type: Opaque
stringData:
  db-user: "usuario"
  db-password: "contraseña"

---
# Deployment para PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: carloscabreravas-dev
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: db-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-name
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U usuario
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U usuario
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        emptyDir: {}

---
# Service para PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: carloscabreravas-dev
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres

---
# Deployment para el microservicio
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  namespace: carloscabreravas-dev
  labels:
    app: microservicio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
      - name: microservicio
        image: carloscabreravas/microservicio:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: microservicio-config
              key: DEBUG
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: microservicio-config
              key: APP_NAME
        - name: API_VERSION
          valueFrom:
            configMapKeyRef:
              name: microservicio-config
              key: API_VERSION
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: db-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-name
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---
# Service para el microservicio
apiVersion: v1
kind: Service
metadata:
  name: microservicio
  namespace: carloscabreravas-dev
  labels:
    app: microservicio
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: microservicio

---
# HorizontalPodAutoscaler para escalado automático
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservicio-hpa
  namespace: carloscabreravas-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservicio
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80